### ISSUE TITLE
Drop support for Python2

### ISSUE THREAD

**Issue by ju-sh** [filyp/autocorrect#2]
Can we focus on Python3 and drop support for Python2 since it has reached end of life?

It would allow the project to use the newer features.

And maybe we should also choose which Python3 version we support? How about >=3.6?

May this fork rejuvante the package. :-)

Edit: I noticed the typo in the last line afterwards. I will leave it there. :D

**Comment by fsondej** [comment]
Hm, I was thinking about that. So far, keeping python2 compatibility was rather easy, so I kept it, in case some people are stuck with the old version for whatever reason. (Although I miss f-strings :/)

If some future improvement turns out to be incompatible with python2 I'm ready to drop that support. Do you have some particular python3 features you'd like to use?

**Comment by ju-sh** [comment]
Yeah, projects still stuck with Python2 can probably manage with the old version anyway.

And yes, who doesn't like fstrings :-D 

The code base is tiny and the needed modification should be easy. Do you mind if I do it?

**Comment by fsondej** [comment]
Sure, go ahead :)

**Comment by ju-sh** [comment]
I made some change at https://github.com/fsondej/autocorrect/pull/4

**Comment by fsondej** [comment]
Awesome, I merged it.
