### ISSUE TITLE
Why the license changes

### ISSUE THREAD

**Issue by ju-sh** [filyp/autocorrect#3]
Hi.

From the commit messages it appears that the project changed its lincese twice in the past month (GPL and LGPL).

And the original project was MIT.

Can you tell us why the changes were made?

**Comment by fsondej** [comment]
Hi!
I just believe that the more open source code in the world, the better, and I thought that using GPL leads to that. Later I realized that pure GPL is way too restrictive and it's actually harmful. The main arguments that convinced me are here:
https://www.linuxjournal.com/article/5935
After some thought I decided LGPL is the best compromise, because it requires people to share their improvements to the library, while making it possible to use the library in closed source projects. It also causes those closed source projects to be 'a bit less closed', because they only link this library, so you can replace it with your custom version if you want.

What are your thoughts on that?

**Comment by ju-sh** [comment]
I was just curious :-)
