### ISSUE TITLE
Add a CONTRIBUTING.md guide

### ISSUE THREAD

**Issue by ju-sh** [filyp/autocorrect#5]
Let's add instructions to guide contributors.

Like specifying the tools and coding style to be used while making contributions.

**Comment by fsondej** [comment]
I added some guidelines. There's not much of them. If you have some ideas for more of them, let me know.

**Comment by ju-sh** [comment]
How about adding a CI/CD pipeline? We can start there and decide on what other tools to use from there.

A mechanism to test the code before merging pull requests would be nice.

**Comment by fsondej** [comment]
I'll try to set that up after my exams, when I have more time.

**Comment by sebincic** [comment]
hi,
i need to add word to spanish's language. How can i do that?
good job

**Comment by ju-sh** [comment]
I'm not sure, but looks like it's the link [here](https://github.com/fsondej/autocorrect/blob/master/autocorrect/constants.py).

**Comment by fsondej** [comment]
@ju-sh yeah, this file defines the location where the dictionaries are stored
@sebincic right now, we don't have a mechanism for adding a single word, we gather the words by processing wikipedia (see [here](https://github.com/fsondej/autocorrect#adding-new-languages)), so I assumed there will be no need to append more words (wikipedia is huge). Maybe your word isn't found, because we cut out the rarely used words, to improve autocorrection (see [here](https://github.com/fsondej/autocorrect/pull/1#issuecomment-637527657)). I wouldn't like to have a mechanism for adding single words to the main repo, because it's too much hassle, and for the reasons in the last link. But I can readd those rare words we cut out, if that would help you. Which word is it?
Also, for the future, when you have a new issue, [start a new github issue](https://github.com/fsondej/autocorrect/issues/new/choose), not use some existing one ;)

**Comment by fsondej** [comment]
I decided that setting up this CI/CD pipeline is an overkill, because contributions are really rare, so I don't think it's worth it. Maybe in the future, if this repo gets more alive I'll set something up.

**Comment by fsondej** [comment]
@ju-sh I got some new traffic in this repo, so I followed your suggestion and set up automatic tests and linting here: https://github.com/fsondej/autocorrect/blob/master/.github/workflows/python-app.yml
